import re

with open("ark_learning_agent/frontend_api.py", "r") as f:
    content = f.read()

replacements = [
    (
        r'@api_router\.post\("/api/chat/delete"\)\nasync def api_chat_delete\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    result = await asyncio\.to_thread\(delete_chat_session, \n        user_id=context\["user_id"\],\n        session_id=str\(payload\.get\("targetSessionId", ""\)\)\.strip\(\),\n    \)',
        '@api_router.post("/api/chat/delete")\nasync def api_chat_delete(request: Request, response: Response, payload: ChatDeleteRequest):\n    context = await _resolve_context(request, response, payload)\n    result = await asyncio.to_thread(delete_chat_session, \n        user_id=context["user_id"],\n        session_id=str(payload.targetSessionId or "").strip(),\n    )'
    ),
    (
        r'@api_router\.post\("/api/chat/delete-all"\)\nasync def api_chat_delete_all\(request: Request, response: Response\):\n    _, context = await _get_payload_and_context\(request, response\)',
        '@api_router.post("/api/chat/delete-all")\nasync def api_chat_delete_all(request: Request, response: Response, payload: ApiRequest):\n    context = await _resolve_context(request, response, payload)'
    ),
    (
        r'@api_router\.post\("/api/diagnostic/start"\)\nasync def api_diagnostic_start\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    app_metrics\["diagnostics_started"\] \+= 1\n    result = await asyncio\.to_thread\(create_assessment, \n        user_id=context\["user_id"\],\n        topic=str\(payload\.get\("topic", ""\)\)\.strip\(\),\n        assessment_type=str\(payload\.get\("assessmentType", "diagnostic"\)\)\.strip\(\) or "diagnostic",\n        level=str\(payload\.get\("level", "beginner"\)\)\.strip\(\) or "beginner",\n        goal=str\(payload\.get\("goal", ""\)\)\.strip\(\),\n        available_time=payload\.get\("availableTime"\),\n        learning_style=str\(payload\.get\("learningStyle", "balanced"\)\)\.strip\(\) or "balanced",\n        question_count=payload\.get\("questionCount", 5\),\n    \)',
        '@api_router.post("/api/diagnostic/start")\nasync def api_diagnostic_start(request: Request, response: Response, payload: DiagnosticStartRequest):\n    context = await _resolve_context(request, response, payload)\n    app_metrics["diagnostics_started"] += 1\n    result = await asyncio.to_thread(create_assessment, \n        user_id=context["user_id"],\n        topic=str(payload.topic or "").strip(),\n        assessment_type=str(payload.assessmentType or "diagnostic").strip() or "diagnostic",\n        level=str(payload.level or "beginner").strip() or "beginner",\n        goal=str(payload.goal or "").strip(),\n        available_time=payload.availableTime,\n        learning_style=str(payload.learningStyle or "balanced").strip() or "balanced",\n        question_count=payload.questionCount or 5,\n    )'
    ),
    (
        r'@api_router\.post\("/api/diagnostic/submit"\)\nasync def api_diagnostic_submit\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    app_metrics\["diagnostics_submitted"\] \+= 1\n    result = await asyncio\.to_thread\(submit_assessment, \n        user_id=context\["user_id"\],\n        assessment_id=str\(payload\.get\("assessmentId", ""\)\)\.strip\(\),\n        answers=payload\.get\("answers"\) or \{\},\n        confidence_by_question=payload\.get\("confidenceByQuestion"\) or \{\},\n    \)',
        '@api_router.post("/api/diagnostic/submit")\nasync def api_diagnostic_submit(request: Request, response: Response, payload: DiagnosticSubmitRequest):\n    context = await _resolve_context(request, response, payload)\n    app_metrics["diagnostics_submitted"] += 1\n    result = await asyncio.to_thread(submit_assessment, \n        user_id=context["user_id"],\n        assessment_id=str(payload.assessmentId or "").strip(),\n        answers=payload.answers or {},\n        confidence_by_question=payload.confidenceByQuestion or {},\n    )'
    ),
    (
        r'@api_router\.post\("/api/roadmap/generate"\)\nasync def api_roadmap_generate\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    app_metrics\["roadmaps_generated"\] \+= 1\n    result = await asyncio\.to_thread\(build_or_update_roadmap, \n        user_id=context\["user_id"\],\n        topic=str\(payload\.get\("topic", ""\)\)\.strip\(\),\n        goal=str\(payload\.get\("goal", ""\)\)\.strip\(\),\n        level=str\(payload\.get\("level", ""\)\)\.strip\(\),\n        available_time=payload\.get\("availableTime"\),\n        deadline_days=payload\.get\("deadlineDays", 14\),\n        start_date=str\(payload\.get\("startDate", ""\)\)\.strip\(\),\n        force_rebuild=bool\(payload\.get\("forceRebuild", False\)\),\n        revision_reason=str\(payload\.get\("revisionReason", ""\)\)\.strip\(\),\n    \)',
        '@api_router.post("/api/roadmap/generate")\nasync def api_roadmap_generate(request: Request, response: Response, payload: RoadmapGenerateRequest):\n    context = await _resolve_context(request, response, payload)\n    app_metrics["roadmaps_generated"] += 1\n    result = await asyncio.to_thread(build_or_update_roadmap, \n        user_id=context["user_id"],\n        topic=str(payload.topic or "").strip(),\n        goal=str(payload.goal or "").strip(),\n        level=str(payload.level or "").strip(),\n        available_time=payload.availableTime,\n        deadline_days=payload.deadlineDays or 14,\n        start_date=str(payload.startDate or "").strip(),\n        force_rebuild=bool(payload.forceRebuild),\n        revision_reason=str(payload.revisionReason or "").strip(),\n    )'
    ),
    (
        r'@api_router\.post\("/api/roadmap/delete"\)\nasync def api_roadmap_delete\(request: Request, response: Response\):\n    _, context = await _get_payload_and_context\(request, response\)',
        '@api_router.post("/api/roadmap/delete")\nasync def api_roadmap_delete(request: Request, response: Response, payload: ApiRequest):\n    context = await _resolve_context(request, response, payload)'
    ),
    (
        r'@api_router\.post\("/api/roadmap/session/update"\)\nasync def api_roadmap_session_update\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    app_metrics\["roadmap_updates"\] \+= 1\n    result = await asyncio\.to_thread\(update_roadmap_session, \n        user_id=context\["user_id"\],\n        phase_id=str\(payload\.get\("phaseId", ""\)\)\.strip\(\),\n        session_id=str\(payload\.get\("sessionId", ""\)\)\.strip\(\),\n        status=str\(payload\.get\("status", ""\)\)\.strip\(\),\n    \)',
        '@api_router.post("/api/roadmap/session/update")\nasync def api_roadmap_session_update(request: Request, response: Response, payload: RoadmapSessionUpdateRequest):\n    context = await _resolve_context(request, response, payload)\n    app_metrics["roadmap_updates"] += 1\n    result = await asyncio.to_thread(update_roadmap_session, \n        user_id=context["user_id"],\n        phase_id=str(payload.phaseId or "").strip(),\n        session_id=str(payload.sessionId or "").strip(),\n        status=str(payload.status or "").strip(),\n    )'
    ),
    (
        r'@api_router\.post\("/api/roadmap/save-google-tasks"\)\nasync def api_roadmap_save_google_tasks\(request: Request, response: Response\):\n    _, context = await _get_payload_and_context\(request, response\)',
        '@api_router.post("/api/roadmap/save-google-tasks")\nasync def api_roadmap_save_google_tasks(request: Request, response: Response, payload: ApiRequest):\n    context = await _resolve_context(request, response, payload)'
    ),
    (
        r'@api_router\.post\("/api/roadmap/session/save-calendar"\)\nasync def api_roadmap_session_save_calendar\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    from \.productivity_mcp_server import create_calendar_event, google_oauth_status\n    user_id = context\["user_id"\]\n    oauth_status = await asyncio\.to_thread\(google_oauth_status, user_id\)\n    if not oauth_status\.get\("connected"\):\n        return \{\n            "status": "auth_required",\n            "message": "Connect Google saves from the account menu before saving calendar events.",\n        \}\n    title = str\(payload\.get\("title", ""\)\)\.strip\(\) or "Roadmap study session"\n    focus = str\(payload\.get\("focus", ""\)\)\.strip\(\)\n    phase_title = str\(payload\.get\("phaseTitle", ""\)\)\.strip\(\)\n    phase_goal = str\(payload\.get\("phaseGoal", ""\)\)\.strip\(\)\n    start_time = str\(payload\.get\("startTime", ""\)\)\.strip\(\)\n    end_time = str\(payload\.get\("endTime", ""\)\)\.strip\(\)\n    if not start_time or not end_time:\n        raise HTTPException\(status_code=HTTPStatus\.BAD_REQUEST, detail="Choose a start time first."\)',
        '@api_router.post("/api/roadmap/session/save-calendar")\nasync def api_roadmap_session_save_calendar(request: Request, response: Response, payload: RoadmapSaveCalendarRequest):\n    context = await _resolve_context(request, response, payload)\n    from .productivity_mcp_server import create_calendar_event, google_oauth_status\n    user_id = context["user_id"]\n    oauth_status = await asyncio.to_thread(google_oauth_status, user_id)\n    if not oauth_status.get("connected"):\n        return {\n            "status": "auth_required",\n            "message": "Connect Google saves from the account menu before saving calendar events.",\n        }\n    title = str(payload.title or "").strip() or "Roadmap study session"\n    focus = str(payload.focus or "").strip()\n    phase_title = str(payload.phaseTitle or "").strip()\n    phase_goal = str(payload.phaseGoal or "").strip()\n    start_time = str(payload.startTime or "").strip()\n    end_time = str(payload.endTime or "").strip()\n    if not start_time or not end_time:\n        raise HTTPException(status_code=HTTPStatus.BAD_REQUEST, detail="Choose a start time first.")'
    ),
    (
        r'@api_router\.post\("/api/materials/upload"\)\nasync def api_materials_upload\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    app_metrics\["materials_uploaded"\] \+= 1\n    result = await asyncio\.to_thread\(save_learning_material, \n        user_id=context\["user_id"\],\n        name=str\(payload\.get\("name", ""\)\)\.strip\(\),\n        mime_type=str\(payload\.get\("mimeType", ""\)\)\.strip\(\),\n        data_base64=str\(payload\.get\("dataBase64", ""\)\)\.strip\(\),\n        pasted_text=str\(payload\.get\("pastedText", ""\)\)\.strip\(\),\n    \)',
        '@api_router.post("/api/materials/upload")\nasync def api_materials_upload(request: Request, response: Response, payload: MaterialsUploadRequest):\n    context = await _resolve_context(request, response, payload)\n    app_metrics["materials_uploaded"] += 1\n    result = await asyncio.to_thread(save_learning_material, \n        user_id=context["user_id"],\n        name=str(payload.name or "").strip(),\n        mime_type=str(payload.mimeType or "").strip(),\n        data_base64=str(payload.dataBase64 or "").strip(),\n        pasted_text=str(payload.pastedText or "").strip(),\n    )'
    ),
    (
        r'@api_router\.post\("/api/materials/tutor"\)\nasync def api_materials_tutor\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    app_metrics\["materials_tutored"\] \+= 1\n    result = await asyncio\.to_thread\(tutor_from_materials, \n        user_id=context\["user_id"\],\n        query=str\(payload\.get\("query", ""\)\)\.strip\(\),\n        material_ids=\[str\(item\) for item in \(payload\.get\("materialIds"\) or \[\]\) if str\(item\)\.strip\(\)\],\n    \)',
        '@api_router.post("/api/materials/tutor")\nasync def api_materials_tutor(request: Request, response: Response, payload: MaterialsTutorRequest):\n    context = await _resolve_context(request, response, payload)\n    app_metrics["materials_tutored"] += 1\n    result = await asyncio.to_thread(tutor_from_materials, \n        user_id=context["user_id"],\n        query=str(payload.query or "").strip(),\n        material_ids=[str(item) for item in (payload.materialIds or []) if str(item).strip()],\n    )'
    ),
    (
        r'@api_router\.post\("/api/materials/mock-test"\)\nasync def api_materials_mock_test\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    result = await asyncio\.to_thread\(create_mock_test_from_materials, \n        user_id=context\["user_id"\],\n        material_ids=\[str\(item\) for item in \(payload\.get\("materialIds"\) or \[\]\) if str\(item\)\.strip\(\)\],\n        topic=str\(payload\.get\("topic", ""\)\)\.strip\(\),\n        level=str\(payload\.get\("level", "beginner"\)\)\.strip\(\) or "beginner",\n        goal=str\(payload\.get\("goal", ""\)\)\.strip\(\),\n        question_count=payload\.get\("questionCount", 5\),\n        structure=str\(payload\.get\("structure", ""\)\)\.strip\(\),\n        sample_style=str\(payload\.get\("sampleStyle", ""\)\)\.strip\(\),\n    \)',
        '@api_router.post("/api/materials/mock-test")\nasync def api_materials_mock_test(request: Request, response: Response, payload: MaterialsMockTestRequest):\n    context = await _resolve_context(request, response, payload)\n    result = await asyncio.to_thread(create_mock_test_from_materials, \n        user_id=context["user_id"],\n        material_ids=[str(item) for item in (payload.materialIds or []) if str(item).strip()],\n        topic=str(payload.topic or "").strip(),\n        level=str(payload.level or "beginner").strip() or "beginner",\n        goal=str(payload.goal or "").strip(),\n        question_count=payload.questionCount or 5,\n        structure=str(payload.structure or "").strip(),\n        sample_style=str(payload.sampleStyle or "").strip(),\n    )'
    ),
    (
        r'@api_router\.post\("/api/materials/delete"\)\nasync def api_materials_delete\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    result = await asyncio\.to_thread\(delete_learning_material, \n        user_id=context\["user_id"\],\n        material_id=str\(payload\.get\("materialId", ""\)\)\.strip\(\),\n    \)',
        '@api_router.post("/api/materials/delete")\nasync def api_materials_delete(request: Request, response: Response, payload: MaterialDeleteRequest):\n    context = await _resolve_context(request, response, payload)\n    result = await asyncio.to_thread(delete_learning_material, \n        user_id=context["user_id"],\n        material_id=str(payload.materialId or "").strip(),\n    )'
    ),
    (
        r'@api_router\.post\("/api/materials/delete-all"\)\nasync def api_materials_delete_all\(request: Request, response: Response\):\n    _, context = await _get_payload_and_context\(request, response\)',
        '@api_router.post("/api/materials/delete-all")\nasync def api_materials_delete_all(request: Request, response: Response, payload: ApiRequest):\n    context = await _resolve_context(request, response, payload)'
    ),
    (
        r'@api_router\.post\("/api/history/delete"\)\nasync def api_history_delete\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    result = await asyncio\.to_thread\(delete_learning_history_item, \n        user_id=context\["user_id"\],\n        record_id=str\(payload\.get\("recordId", ""\)\)\.strip\(\),\n    \)',
        '@api_router.post("/api/history/delete")\nasync def api_history_delete(request: Request, response: Response, payload: HistoryDeleteRequest):\n    context = await _resolve_context(request, response, payload)\n    result = await asyncio.to_thread(delete_learning_history_item, \n        user_id=context["user_id"],\n        record_id=str(payload.recordId or "").strip(),\n    )'
    ),
    (
        r'@api_router\.post\("/api/history/delete-all"\)\nasync def api_history_delete_all\(request: Request, response: Response\):\n    _, context = await _get_payload_and_context\(request, response\)',
        '@api_router.post("/api/history/delete-all")\nasync def api_history_delete_all(request: Request, response: Response, payload: ApiRequest):\n    context = await _resolve_context(request, response, payload)'
    ),
    (
        r'@api_router\.post\("/api/report/generate"\)\nasync def api_report_generate\(request: Request, response: Response\):\n    _, context = await _get_payload_and_context\(request, response\)',
        '@api_router.post("/api/report/generate")\nasync def api_report_generate(request: Request, response: Response, payload: ApiRequest):\n    context = await _resolve_context(request, response, payload)'
    ),
    (
        r'@api_router\.post\("/api/report/save-google-doc"\)\nasync def api_report_save_google_doc\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    app_metrics\["reports_saved_to_docs"\] \+= 1\n    from \.productivity_mcp_server import google_oauth_status, save_weekly_report_doc\n    user_id = context\["user_id"\]\n    oauth_status = await asyncio\.to_thread\(google_oauth_status, user_id\)\n    if not oauth_status\.get\("connected"\):\n        return \{\n            "status": "auth_required",\n            "message": "Connect Google saves from the account menu before saving reports.",\n        \}\n    result = await asyncio\.to_thread\(save_weekly_report_doc, \n        user_id=user_id,\n        title=str\(payload\.get\("title", ""\)\)\.strip\(\),\n    \)',
        '@api_router.post("/api/report/save-google-doc")\nasync def api_report_save_google_doc(request: Request, response: Response, payload: ReportSaveDocRequest):\n    context = await _resolve_context(request, response, payload)\n    app_metrics["reports_saved_to_docs"] += 1\n    from .productivity_mcp_server import google_oauth_status, save_weekly_report_doc\n    user_id = context["user_id"]\n    oauth_status = await asyncio.to_thread(google_oauth_status, user_id)\n    if not oauth_status.get("connected"):\n        return {\n            "status": "auth_required",\n            "message": "Connect Google saves from the account menu before saving reports.",\n        }\n    result = await asyncio.to_thread(save_weekly_report_doc, \n        user_id=user_id,\n        title=str(payload.title or "").strip(),\n    )'
    ),
    (
        r'@api_router\.post\("/api/assessment/save-google-doc"\)\nasync def api_assessment_save_google_doc\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    from \.productivity_mcp_server import google_oauth_status, save_assessment_doc\n    user_id = context\["user_id"\]\n    oauth_status = await asyncio\.to_thread\(google_oauth_status, user_id\)\n    if not oauth_status\.get\("connected"\):\n        return \{\n            "status": "auth_required",\n            "message": "Connect Google saves from the account menu before saving assessments.",\n        \}\n    result = await asyncio\.to_thread\(save_assessment_doc, \n        user_id=user_id,\n        assessment_id=str\(payload\.get\("assessmentId", ""\)\)\.strip\(\),\n        title=str\(payload\.get\("title", ""\)\)\.strip\(\),\n    \)',
        '@api_router.post("/api/assessment/save-google-doc")\nasync def api_assessment_save_google_doc(request: Request, response: Response, payload: AssessmentSaveDocRequest):\n    context = await _resolve_context(request, response, payload)\n    from .productivity_mcp_server import google_oauth_status, save_assessment_doc\n    user_id = context["user_id"]\n    oauth_status = await asyncio.to_thread(google_oauth_status, user_id)\n    if not oauth_status.get("connected"):\n        return {\n            "status": "auth_required",\n            "message": "Connect Google saves from the account menu before saving assessments.",\n        }\n    result = await asyncio.to_thread(save_assessment_doc, \n        user_id=user_id,\n        assessment_id=str(payload.assessmentId or "").strip(),\n        title=str(payload.title or "").strip(),\n    )'
    ),
    (
        r'@api_router\.post\("/api/chat"\)\nasync def api_chat\(request: Request, response: Response\):\n    payload, context = await _get_payload_and_context\(request, response\)\n    \n    user_id = context\["user_id"\]\n    session_id = context\["session_id"\]\n    message = str\(payload\.get\("message", ""\)\)\.strip\(\)\n    user_timezone = str\(payload\.get\("timezone", ""\)\)\.strip\(\)\n    selected_material_ids = \[\n        str\(item\) for item in \(payload\.get\("selectedMaterialIds"\) or \[\]\) if str\(item\)\.strip\(\)\n    \]\n    input_mode = str\(payload\.get\("inputMode", ""\)\)\.strip\(\)\.lower\(\)\n    temporary_attachment_context, temporary_attachment_metadata = _build_temporary_attachment_context\(\n        payload\.get\("temporaryAttachments"\)\n    \)',
        '@api_router.post("/api/chat")\nasync def api_chat(request: Request, response: Response, payload: ChatRequest):\n    context = await _resolve_context(request, response, payload)\n    \n    user_id = context["user_id"]\n    session_id = context["session_id"]\n    message = str(payload.message or "").strip()\n    user_timezone = str(payload.timezone or "").strip()\n    selected_material_ids = [\n        str(item) for item in (payload.selectedMaterialIds or []) if str(item).strip()\n    ]\n    input_mode = str(payload.inputMode or "").strip().lower()\n    temporary_attachment_context, temporary_attachment_metadata = _build_temporary_attachment_context(\n        payload.temporaryAttachments\n    )'
    )
]

for pat, repl in replacements:
    content, count = re.subn(pat, repl, content, count=1)
    if count == 0:
        print(f"Failed to match: {pat[:50]}...")
    else:
        print(f"Successfully matched: {pat[:50]}...")

with open("ark_learning_agent/frontend_api.py", "w") as f:
    f.write(content)

